export const CUSTOM_SERVICES = [
    {
        "service": 1000,
        "name": "💚 Instagram Channel Member Global ➜ [ Start : 0-6 Hours | Speed : 10K+/Day | Refill : No | Quality : High ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.8490",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1001,
        "name": "💙 Instagram Channel Members [Nigeria 🇳🇬] [Max 100K] | [HQ] [Day 10K]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.8644",
        "min": "10",
        "max": "1000000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1002,
        "name": "💙 Instagram Comment Likes With Link ➜ [ Start 0-1 Hour | Speed : 5K/Day | Refill : No | Drop : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "3.7431",
        "min": "10",
        "max": "20000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1003,
        "name": "💙 Instagram Comment Likes With Username ➜ [ Start 0-1 Hour | Speed : 5K/Day | Refill : No | Drop : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "3.7431",
        "min": "10",
        "max": "20000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1004,
        "name": "💚 Instagram Comment Likes ➜ [ Speed : 1K/Day | Refill : No | Drop : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "4.1714",
        "min": "20",
        "max": "10000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1005,
        "name": "💙 Instagram Custom Comments ➜ [ Speed : 100+/Day | Refill : No | Drop : No | Quality : Real - HQ - 300/5000 Follower Profil ] - Premium",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "208.3725",
        "min": "1",
        "max": "200",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1006,
        "name": "💚 Instagram Custom Comments ➜ [ Speed : 1K/Day | Refill : No Refill ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "11.4055",
        "min": "5",
        "max": "1000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1007,
        "name": "💙 Instagram Custom Comments ➜ [ Speed : 500+/Day | Refill : No | Drop : No | Quality : Real - HQ ] - Sv1",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "154.3500",
        "min": "1",
        "max": "1000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1008,
        "name": "💚 Instagram Custom Comments ➜ [ Speed : 5K/Day | Refill : No | Drop : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "17.9663",
        "min": "1",
        "max": "20000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1009,
        "name": "💚 Instagram Emoji Comments ➜ [ Speed : 1K/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "8.8906",
        "min": "1",
        "max": "1000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1010,
        "name": "💚 Instagram Emoji Comments ➜ [ Speed : 1K/Day | Refill : No | Drop : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "8.0262",
        "min": "1",
        "max": "1000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1011,
        "name": "💚 Instagram Female Custom Comments ➜ [ Speed : 50/Day | Refill : No | Drop : No | Quality : High ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "24.1107",
        "min": "1",
        "max": "300",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1012,
        "name": "💚 Instagram Male Custom Comments ➜ [ Speed : 50/Day | Refill : No | Drop : No | Quality : High ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "24.0786",
        "min": "1",
        "max": "150",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1013,
        "name": "💚 Instagram Negative Emoji Comments ➜ [ Speed : 5K/Day | Refill : No | Drop : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "7.7175",
        "min": "10",
        "max": "20000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1014,
        "name": "💙 Instagram Positive Random Comment ➜ [ Speed : 100 | Refil : No Refil | Quality : Real - HQ ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "77.1750",
        "min": "5",
        "max": "100",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1015,
        "name": "💙 Instagram Positive Random Comments ➜ [ Speed : 100+/Day | Refill : No | Drop : No | Quality : Real - HQ - 300/5000 Follower Profil ] - Premium",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "200.6550",
        "min": "1",
        "max": "200",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1016,
        "name": "💚 Instagram Random Emoji Comments ➜ [ Speed : 1K/Day | Refill : 30 Days | Drop : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "9.6314",
        "min": "1",
        "max": "1000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1017,
        "name": "💚 Instagram Random Emoji Comments ➜ [ Speed : 5K/Day | Refill : No | Drop : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "7.7175",
        "min": "1",
        "max": "20000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1018,
        "name": "↓↓~~~~~~~~~~~~~~~~~~~~ Not Guaranteed ~~~~~~~~~~~~~~~~~~~~↓↓",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1234798.7652",
        "min": "999",
        "max": "9999999",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1019,
        "name": "💙 Instagram Followers ➜ [ Speed : 100k+/Day | Refill : 365 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "4.0752",
        "min": "10",
        "max": "10000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1020,
        "name": "💙 Instagram Followers ➜ [ Speed : 10k+/Day | Refill : 365 Days | Quality : %100 Real + HQ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "8.3498",
        "min": "10",
        "max": "10000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1021,
        "name": "💚 Instagram Followers ➜ [ Speed : 200K+/Day | Refill : 30 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "4.5650",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1022,
        "name": "💙 Instagram Followers ➜ [ Speed : 20k+/Day | Refill : No | Quality : %100 Real + HQ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "2.7390",
        "min": "1",
        "max": "5000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1023,
        "name": "💛 Instagram Followers ➜ [ Speed : 40k+/Day | Refill : 30 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "3.5844",
        "min": "10",
        "max": "10000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1024,
        "name": "💚 Instagram Followers ➜ [ Speed : 40k+/Day | Refill : 30 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "2.8471",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1025,
        "name": "💚 Instagram Followers ➜ [ Speed : 45K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "3.5844",
        "min": "10",
        "max": "10000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1026,
        "name": "💛 Instagram Followers ➜ [ Speed : 5K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "2.6112",
        "min": "10",
        "max": "100000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1027,
        "name": "💙 Instagram Followers ➜ [ 𝗙𝗢𝗥 𝗙𝗟𝗔𝗚 𝗢𝗙𝗙 | Speed : 100K+/Day | Refill : 365 Days | Quality : Real ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "5.3251",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1028,
        "name": "💛 Instagram Followers ➜ [ 𝗙𝗢𝗥 𝗙𝗟𝗔𝗚 𝗢𝗙𝗙 | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "2.0838",
        "min": "21",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1029,
        "name": "💚 Instagram Followers ➜ [ 𝗙𝗢𝗥 𝗙𝗟𝗔𝗚 𝗢𝗙𝗙 | Speed : 30K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "2.1609",
        "min": "20",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1030,
        "name": "💛 Instagram Followers ➜ [ 𝗙𝗢𝗥 𝗙𝗟𝗔𝗚 𝗢𝗙𝗙 | Speed : 50k+/Day | Refill : 15 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "4.4762",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1031,
        "name": "💙 Instagram Followers ➜ [ 𝗙𝗢𝗥 𝗙𝗟𝗔𝗚 𝗢𝗙𝗙 |Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "2.3153",
        "min": "50",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1032,
        "name": "💚 Instagram Followers ➜ [ 𝗙𝗢𝗥 𝗙𝗟𝗔𝗚 𝗢𝗙𝗙| Speed : 50K+/Day | Refill : 30 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "4.7849",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1033,
        "name": "💚 Instagram Followers ➜ | Speed : 25K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "3.1642",
        "min": "10",
        "max": "5000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1034,
        "name": "Instagram Followers ➜ [ Speed : 20K+/Day | Refill: 30 Days | Quality : Old Accounts ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "4.9392",
        "min": "20",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1035,
        "name": "Instagram Followers ➜ [ Speed : 20K+/Day | Refill: No | Quality : Old Accounts ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "4.6305",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1036,
        "name": "1.000.000 Instagram Premium Global Followers ➜ [ Refill: 365 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1778.1120",
        "min": "1",
        "max": "1",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1037,
        "name": "100.000 Instagram Premium Global Followers ➜ [ Refill: 365 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "197.5556",
        "min": "1",
        "max": "1",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1038,
        "name": "2.000.000 Instagram Premium Global Followers ➜ [ Refill: 365 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "3556.2116",
        "min": "1",
        "max": "1",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1039,
        "name": "250.000 Instagram Premium Global Followers ➜ [ Refill: 365 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "487.7460",
        "min": "1",
        "max": "1",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1040,
        "name": "50.000 Instagram Premium Global Followers ➜ [ Refill: 365 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "98.7717",
        "min": "1",
        "max": "1",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1041,
        "name": "500.000 Instagram Premium Global Followers ➜ [ Refill: 365 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "975.4920",
        "min": "1",
        "max": "1",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1042,
        "name": "↓↓~~~~~~~~~~~~~~~~~~~~ Engagement ~~~~~~~~~~~~~~~~~~~~↓↓",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "12346.7652",
        "min": "9999",
        "max": "9999",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1043,
        "name": "↓↓~~~~~~~~~~~~~~~~~~~~ Profile Visits ~~~~~~~~~~~~~~~~~~~~↓↓",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "12346.7652",
        "min": "9999",
        "max": "9999",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1044,
        "name": "↓↓~~~~~~~~~~~~~~~~~~~~ Reach ~~~~~~~~~~~~~~~~~~~~↓↓",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "12346.7652",
        "min": "9999",
        "max": "9999",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1045,
        "name": "↓↓~~~~~~~~~~~~~~~~~~~~ Save ~~~~~~~~~~~~~~~~~~~~↓↓",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "12346.7652",
        "min": "999",
        "max": "99999",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1046,
        "name": "↓↓~~~~~~~~~~~~~~~~~~~~ Shares ~~~~~~~~~~~~~~~~~~~~↓↓",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "12346.7652",
        "min": "9999",
        "max": "9999",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1047,
        "name": "↓↓~~~~~~~~~~~~~~~~~~~~ Story ~~~~~~~~~~~~~~~~~~~~↓↓",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "123478.7652",
        "min": "999",
        "max": "999999",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1048,
        "name": "💚 Instagram ALL Story Views ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1460",
        "min": "10",
        "max": "15000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1049,
        "name": "💛 Instagram ALL Story Views ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0042",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1050,
        "name": "💚 Instagram All Story Views ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No | Stable ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1004",
        "min": "50",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1051,
        "name": "💚 Instagram Engagement + Shares + Reach + Profile Visits+ Impressions ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.3777",
        "min": "100",
        "max": "100000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1052,
        "name": "💚 Instagram Engagement + Shares ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.6561",
        "min": "100",
        "max": "100000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1053,
        "name": "💚 Instagram Engagement+ Shares + Reach + Impressions ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.3120",
        "min": "100",
        "max": "100000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1054,
        "name": "💚 Instagram Fragmented Story Views ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1081",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1055,
        "name": "💙 Instagram Impressions ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0300",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1056,
        "name": "💙 Instagram Impressions + Reach ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1158",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1057,
        "name": "💙 Instagram Impressions + Reach + Profile Visits ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0541",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1058,
        "name": "💙 Instagram Impressions + Reach + Profile Visits ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1961",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1059,
        "name": "💙 Instagram Impressions + Reach + Profile Visits ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.3474",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1060,
        "name": "💙 Instagram Impressions + Reach ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0368",
        "min": "10",
        "max": "500000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1061,
        "name": "💙 Instagram Impressions - Explore ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1110",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1062,
        "name": "💙 Instagram Impressions - Explore+ Home+Discover Others ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1110",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1063,
        "name": "💙 Instagram Impressions - Others ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1110",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1064,
        "name": "💙 Instagram Impressions [ Explore - Home - Location - Profile ]➜ [ 100K/Day | No Refill ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1081",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1065,
        "name": "💙 Instagram Impressions [ Photo + Explore + Home ] ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0696",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1066,
        "name": "💙 Instagram Impressions ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0653",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1067,
        "name": "💙 Instagram Impressions ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0711",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1068,
        "name": "💙 Instagram Impressions ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0926",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1069,
        "name": "💙 Instagram Impressions ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1079",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1070,
        "name": "💙 Instagram Impressions ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1081",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1071,
        "name": "💙 Instagram Impressions ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1110",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1072,
        "name": "💙 Instagram Impressions ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1158",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1073,
        "name": "💙 Instagram Impressions ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1544",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1074,
        "name": "💙 Instagram Impressions ➜ [ Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1541",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1075,
        "name": "💚 Instagram Post Share ➜ [ Start : 0--60 Minutes | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0185",
        "min": "100",
        "max": "500000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1076,
        "name": "💚 Instagram Post Share ➜ [ Start : 0-60 Minutes | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0170",
        "min": "20",
        "max": "100000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1077,
        "name": "💙 Instagram Profile Reach ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1459",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1078,
        "name": "💙 Instagram Profile Visits + Views ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1930",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1079,
        "name": "💙 Instagram Profile Visits + Reach ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1459",
        "min": "100",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1080,
        "name": "💙 Instagram Profile Visits + Reach +Impressions ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1158",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1081,
        "name": "💙 Instagram Profile Visits + Views ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.3506",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1082,
        "name": "💙 Instagram Profile Visits ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0387",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1083,
        "name": "💙 Instagram Profile Visits ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1258",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1084,
        "name": "💙 Instagram Reach + Explore Impressions ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0772",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1085,
        "name": "💙 Instagram Reach + Impressions ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0772",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1086,
        "name": "💙 Instagram Reach + Impressions ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1305",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1087,
        "name": "💙 Instagram Reach + Impressions ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1256",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1088,
        "name": "💙 Instagram Reach + Impressions ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.2542",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1089,
        "name": "💙 Instagram Reach + Impressions ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.7717",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1090,
        "name": "💙 Instagram Reach + Impressions ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0772",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1091,
        "name": "💙 Instagram Reach + Impressions ➜ [ Start : 0-1 Hour | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0772",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1092,
        "name": "💙 Instagram Reach + Profile Visits Impressions ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.8490",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1093,
        "name": "💚 Instagram Save ➜ [ Medium Quality | 10K/Day | No Refill ] ⛔",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0903",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1094,
        "name": "💚 Instagram Save ➜ [ Medium Quality | 50K/Day | No Refill ] ⛔",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0042",
        "min": "10",
        "max": "200000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1095,
        "name": "💚 Instagram Save ➜ [ Start : 0-1 Hour | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0926",
        "min": "50",
        "max": "10000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1096,
        "name": "💙 Instagram Shares ➜ [ Start : 0-2 Hours | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.2741",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1097,
        "name": "💙 Instagram Shares ➜ [ Start : 0-2 Hours | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.3859",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1098,
        "name": "💙 Instagram Shares ➜ [ Start : 0-24 Hours | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0677",
        "min": "100",
        "max": "500000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1099,
        "name": "💚 Instagram Story Impression + Profile Visit + Shares + Next ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.0804",
        "min": "100",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1100,
        "name": "💚 Instagram Story Impression All Posts ➜ [ Put Username | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.7717",
        "min": "100",
        "max": "10000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1101,
        "name": "💚 Instagram Story Impression ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.2316",
        "min": "100",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1102,
        "name": "💚 Instagram Story Link Clicks ➜ [ Start : 0-15 Minutes | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.3891",
        "min": "100",
        "max": "250000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1103,
        "name": "💚 Instagram Story Profile Visits ➜ [ Start : 0-15 Minutes | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.7717",
        "min": "100",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1104,
        "name": "💚 Instagram Story Quiz = 1 ➜ [ Start : 0-15 Minutes | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.3120",
        "min": "100",
        "max": "10000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1105,
        "name": "💚 Instagram Story Quiz = 2 ➜ [ Start : 0-15 Minutes | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.3120",
        "min": "100",
        "max": "10000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1106,
        "name": "💚 Instagram Story Quiz = 3 ➜ [ Start : 0-15 Minutes | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.3891",
        "min": "100",
        "max": "10000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1107,
        "name": "💚 Instagram Story Quiz = 4 ➜ [ Start : 0-15 Minutes | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.3891",
        "min": "100",
        "max": "10000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1108,
        "name": "💚 Instagram Story Share ➜ [ Start : 0-15 Minutes | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.3859",
        "min": "100",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1109,
        "name": "💚 Instagram Story Story Slider ➜ [ Start : 0-15 Minutes | Speed : 50K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.2348",
        "min": "100",
        "max": "10000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1110,
        "name": "💚 Instagram Story Views + Impression ➜ [ ALL Stories | Start : 0-1 Hour | Speed : 100K+/Day | Refill : No | Stable ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1852",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1111,
        "name": "💛 Instagram Story Views + Impressions ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.0772",
        "min": "10",
        "max": "100000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1112,
        "name": "💚 Instagram Story Views ➜ [ ALL Stories | Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1081",
        "min": "100",
        "max": "30000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1113,
        "name": "💚 Instagram Story Views ➜ [ ALL Stories | Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1081",
        "min": "100",
        "max": "5000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1114,
        "name": "💚 Instagram Story Views ➜ [ ALL Stories | Start : 0-1 Hour | Speed : 100K+/Day | Refill : No | Quality : Medium ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1158",
        "min": "100",
        "max": "20000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1115,
        "name": "💚 Instagram Story Views ➜ [ ALL Stories | Start : 0-1 Hour | Speed : 100K+/Day | Refill : No | Stable ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.1235",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1116,
        "name": "💚 Instagram Story Vote = 1 ➜ [ Start : 0-1 Hour | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.3891",
        "min": "100",
        "max": "10000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1117,
        "name": "💚 Instagram Story Vote = 2 ➜ [ Start : 0-1 Hour | Speed : 10K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.3891",
        "min": "100",
        "max": "10000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1118,
        "name": "💙 Instagram Video Reach ➜ [ Start : 0-1 Hour | Speed : 100K+/Day | Refill : No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.5557",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1119,
        "name": "💙 Instagram Likes ➜ [ Speed : 100k+/Day | Refill : 30 Days | Drop : 30 Days | Quality : Real + Active]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.0590",
        "min": "100",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1120,
        "name": "💛 Instagram Likes ➜ [ Speed : 50K+/ Day : Refill: No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.7717",
        "min": "20",
        "max": "100000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1121,
        "name": "💙 Instagram Likes ➜ [ Speed : 100k+/Day | Refill : 30 Days | Quality : Real + Active]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.9878",
        "min": "10",
        "max": "100000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1122,
        "name": "💛 Instagram Likes ➜ [ Speed : 20K+/ Day : Refill: No ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.7409",
        "min": "100",
        "max": "100000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1123,
        "name": "💚 Instagram Likes ➜ [ Speed : 40K+/ Day : Refill: 30 Days ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.1113",
        "min": "100",
        "max": "100000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1124,
        "name": "💚 Instagram Likes ➜ [ Speed : 45K+/ Day : Refill: No Refil ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.4631",
        "min": "10",
        "max": "1000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1125,
        "name": "💚 Instagram Likes ➜ [ Speed : 55K+/ Day : Refill: No Refill ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.6946",
        "min": "10",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1126,
        "name": "↓↓~~~~~~~~~~~~~~~~~~~~High Quality~~~~~~~~~~~~~~~~~~~~↓↓",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1233.5652",
        "min": "999",
        "max": "999",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1127,
        "name": "💛 Instagram Livestream Views ➜ [ Refill : No | Stay For : 15 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "0.8891",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1128,
        "name": "💛 Instagram Livestream Views ➜ [ Refill : No | Stay For : 120 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "7.1124",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1129,
        "name": "💛 Instagram Livestream Views ➜ [ Refill : No | Stay For : 180 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "10.6687",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1130,
        "name": "💛 Instagram Livestream Views ➜ [ Refill : No | Stay For : 240 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "14.2249",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1131,
        "name": "💛 Instagram Livestream Views ➜ [ Refill : No | Stay For : 30 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "1.7781",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1132,
        "name": "💛 Instagram Livestream Views ➜ [ Refill : No | Stay For : 360 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "21.3373",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1133,
        "name": "💛 Instagram Livestream Views ➜ [ Refill : No | Stay For : 60 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "3.5562",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1134,
        "name": "💛 Instagram Livestream Views ➜ [ Refill : No | Stay For : 720 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "21.3373",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1135,
        "name": "💛 Instagram Livestream Views ➜ [ Refill : No | Stay For : 90 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "5.3343",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1136,
        "name": "💙 Instagram Livestream Views ➜ [ Speed : Fast | Refill : No | Stay For : 120 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "21.6090",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1137,
        "name": "💙 Instagram Livestream Views ➜ [ Speed : Fast | Refill : No | Stay For : 180 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "32.4135",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1138,
        "name": "💙 Instagram Livestream Views ➜ [ Speed : Fast | Refill : No | Stay For : 30 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "6.1740",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1139,
        "name": "💙 Instagram Livestream Views ➜ [ Speed : Fast | Refill : No | Stay For : 360 Minutes ]",
        "type": "default",
        "category": "Instagram Followers",
        "rate": "64.8270",
        "min": "100",
        "max": "50000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1140,
        "name": "Elite Booster Growth Package ➜ [ 30 Days ] [ READ DESCRIPTION ❗️] 🚀",
        "type": "default",
        "category": "13829760",
        "rate": "203.7420",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1141,
        "name": "Imperial Prestige Growth Package ➜ [ 30 Days ] [ READ DESCRIPTION ❗️] 👑",
        "type": "default",
        "category": "13829760",
        "rate": "4321.8000",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1142,
        "name": "Mega Influencer Growth Package ➜ [ 30 Days ] [ READ DESCRIPTION ❗️] 🔥",
        "type": "default",
        "category": "13829760",
        "rate": "679.1400",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1143,
        "name": "Prestige Influencer Growth Package ➜ [ 30 Days ] [ READ DESCRIPTION ❗️] 👑",
        "type": "default",
        "category": "13829760",
        "rate": "432.1800",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1144,
        "name": "Pro Creator Growth Package ➜ [ 30 Days ] [ READ DESCRIPTION ❗️] 💎",
        "type": "default",
        "category": "13829760",
        "rate": "166.6980",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1145,
        "name": "Royal Diamond Growth Package ➜ [ 30 Days ] [ READ DESCRIPTION ❗️] 💎",
        "type": "default",
        "category": "13829760",
        "rate": "2469.6000",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1146,
        "name": "Starter Growth Package ➜ [ 30 Days ] [ READ DESCRIPTION ❗️] 🚀",
        "type": "default",
        "category": "13829760",
        "rate": "30.8700",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1147,
        "name": "Titan Silver Growth Package ➜ [ 30 Days ] [ READ DESCRIPTION ❗️] 🚀",
        "type": "default",
        "category": "13829760",
        "rate": "679.1400",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1148,
        "name": "Ultra Platinum Growth Package ➜ [ 30 Days ] [ READ DESCRIPTION ❗️] 💎",
        "type": "default",
        "category": "13829760",
        "rate": "1173.0600",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1149,
        "name": "Ultra Silver Growth Package ➜ [ 30 Days ] [ READ DESCRIPTION ❗️] 🚀",
        "type": "default",
        "category": "13829760",
        "rate": "617.4000",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1150,
        "name": "💚 Instagram Repost ➜ [ Max 20 | Real Active Accounts with followers | Starts Fast ]",
        "type": "default",
        "category": "13829760",
        "rate": "773.2160",
        "min": "1",
        "max": "20",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1151,
        "name": "💚 Instagram Repost ➜ [ Max 50 | Real Active Accounts with followers | Starts Fast ]",
        "type": "default",
        "category": "13829760",
        "rate": "773.2160",
        "min": "1",
        "max": "50",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1152,
        "name": "💚 Instagram Repost ➜ [ Max 500 | 100% Worldwide | Starts Fast ]",
        "type": "default",
        "category": "13829760",
        "rate": "99.4135",
        "min": "10",
        "max": "500",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1153,
        "name": "💚 Instagram Views ➜ [ Speed : +100K / Day | Refill : 30 Days | Instant ]",
        "type": "default",
        "category": "13829760",
        "rate": "0.0089",
        "min": "100",
        "max": "1000000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1154,
        "name": "💚 Instagram Views ➜ [ Speed : +100K / Day | Refill : No Refill | Instant ]",
        "type": "default",
        "category": "13829760",
        "rate": "0.0029",
        "min": "100",
        "max": "100000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1155,
        "name": "💛 Instagram Views ➜ [ Speed : +100k/ Day | Refill : No | Instant ]",
        "type": "default",
        "category": "13829760",
        "rate": "0.0016",
        "min": "10",
        "max": "1000000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1156,
        "name": "💛 Instagram Views ➜ [ Speed : +150k/ Day | Refill : No | Instant ]",
        "type": "default",
        "category": "13829760",
        "rate": "0.0018",
        "min": "100",
        "max": "1000000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1157,
        "name": "💙 Instagram Views ➜ [ Speed : 50k/ Day | Refill : 30 Days | Instant ]",
        "type": "default",
        "category": "13829760",
        "rate": "0.0134",
        "min": "100",
        "max": "1000000000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1158,
        "name": "💙 Instagram African Followers ➜ [ High Quality | Max: 5K | Refill: 30 Days ] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "23.1525",
        "min": "100",
        "max": "5000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1159,
        "name": "💙 Instagram Followers ➜ [ EASTERN AFRICA ]",
        "type": "default",
        "category": "385258",
        "rate": "23.1525",
        "min": "1000",
        "max": "1000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1160,
        "name": "💙 Instagram Followers ➜ [ SOUTHERN AFRICA ]",
        "type": "default",
        "category": "385258",
        "rate": "23.1525",
        "min": "1000",
        "max": "1000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1161,
        "name": "💙 Instagram Followers ➜ [ WESTERN AFRICA ]",
        "type": "default",
        "category": "385258",
        "rate": "23.1525",
        "min": "1000",
        "max": "1000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1162,
        "name": "💙 Instagram Nigeria Comments [5K] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "30.8700",
        "min": "50",
        "max": "5000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1163,
        "name": "💙 Instagram Nigeria Comments [AUTO] [5K] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "30.8700",
        "min": "50",
        "max": "5000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1164,
        "name": "💙 Instagram Nigeria Comments ➜ [ Medium Quality | Max: 5K | No Drop ] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "30.8700",
        "min": "50",
        "max": "5000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1165,
        "name": "💙 Instagram Nigeria Comments ➜ [ UNIQUE VOTES ]",
        "type": "default",
        "category": "385258",
        "rate": "30.8700",
        "min": "50",
        "max": "5000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1166,
        "name": "💙 Instagram Nigeria Followers [10K] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "38.5875",
        "min": "200",
        "max": "10000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1167,
        "name": "💙 Instagram Nigeria Followers [5K] [S2] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "46.3050",
        "min": "100",
        "max": "5000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1168,
        "name": "💙 Instagram Nigeria Followers [S3] [100K] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "23.1525",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1169,
        "name": "💙 Instagram Nigeria Followers [S4] [50K] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "15.4350",
        "min": "1",
        "max": "1",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1170,
        "name": "💙 Instagram Nigeria Followers ➜ [ High Quality | Max: 10K | No Refill ] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "38.5875",
        "min": "200",
        "max": "10000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1171,
        "name": "💙 Instagram Nigeria Followers ➜ [ High Quality | Max: 3K | Refill: 30 Days ] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "5.9122",
        "min": "5",
        "max": "3000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1172,
        "name": "💙 Instagram Nigeria Followers ➜ [ High Quality | Max: 5K | No Refill ] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "46.3050",
        "min": "100",
        "max": "5000",
        "refill": true,
        "cancel": true
    },
    {
        "service": 1173,
        "name": "💙 Instagram Nigeria Likes [5K] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "30.8700",
        "min": "100",
        "max": "5000",
        "refill": false,
        "cancel": true
    },
    {
        "service": 1174,
        "name": "💙 Instagram Nigeria Likes [AUTO] [5K] 🇳🇬",
        "type": "default",
        "category": "385258",
        "rate": "30.8700",
        "min": "100",
        "max": "5000",
        "refill": false,
        "cancel": true
    }
];